# Generated by Django 3.2.12 on 2022-04-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('password', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=3)),
                ('nickname', models.CharField(max_length=20)),
            ],
        ),
    ]
