# Generated by Django 3.2.12 on 2022-05-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 존재하는 닉네임입니다.'}, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(error_messages={'unique': '이미 존재하는 이름입니다.'}, max_length=8, unique=True),
        ),
    ]
