# Generated by Django 3.2.12 on 2022-05-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'max_length': '닉네임이 5글자 이내인지 확인해주세요.', 'unique': '이미 존재하는 닉네임입니다.'}, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(error_messages={'max_length': '이름이 5글자 이내인지 확인해주세요.', 'unique': '이미 존재하는 이름입니다.'}, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'max_length': '아이디가 10글자 이내인지 확인해주세요.', 'unique': '이미 존재하는 아이디입니다.'}, max_length=10, unique=True, verbose_name='username'),
        ),
    ]
