# Generated by Django 3.2.12 on 2022-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220514_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '이미 존재하는 이메일입니다.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'max_length': '닉네임이 10글자 이내인지 확인해주세요.', 'unique': '이미 존재하는 닉네임입니다.'}, max_length=10, unique=True),
        ),
    ]
