# Generated by Django 3.2.12 on 2022-05-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll_paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollpaper',
            name='title',
            field=models.CharField(error_messages={'unique': '제목 길이가 최대 35자인지 확인해주세요.'}, max_length=35),
        ),
    ]
