# Generated by Django 3.2.12 on 2022-05-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll_paper', '0002_alter_rollpaper_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollpaper',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
