# Generated by Django 3.2.12 on 2022-05-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll_paper', '0003_alter_rollpaper_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollpaper',
            name='title',
            field=models.CharField(error_messages={'max_length': '제목이 35글자 이내인지 확인해주세요'}, max_length=35),
        ),
    ]
